
- hosts: localhost
  tasks:
    - name: Install Git
      become: yes
      become_method: sudo
      yum: name=git state=latest

    - name: clone xura
      git: repo=https://github.com/dmendel1/xura.git dest=/worksplace/xura update=no

    - name: Creates directory
      file: pathworks=/workspace/build2 state=directory

    - name: copy Dockerfile
      copy: src=/workspace/xura/Dockerfile dest=/workspace/build2/
