
- hosts: localhost
  tasks:
    - name: Install Git
      become: yes
      become_method: sudo
      yum: name=git state=latest

    - name: Install Docker
      become: yes
      become_method: sudo
      yum: name=docker state=latest

    - name: clone xura
      git: repo=https://github.com/dmendel1/xura.git dest=xura update=no

    - name: clone David pet
      git: repo=https://github.com/dmendel1/spring-petclinic.git dest=spring-petclinic update=no
